language: python
os: linux
if: branch = master or tag IS present
python: 3.6

before_script:
    - pip install -r packages/rkt_armutils/requirements.txt
    - pip install -r packages/rkt_ciutils/requirements.txt
    - pip install -r packages/rkt_utils/requirements.txt
    - pip install rkd==2.1.0.0rc2.dev2 rkd-python==2.1.0.0rc2.dev2

jobs:
    allow_failures:
        env:
            - CAN_FAIL=true

    include:
        - stage: Build on Python 3.6
          python: 3.6
          script:
              - rkd :build

        - stage: Build on Python 3.7
          python: 3.6
          script:
              - rkd :build

        - stage: Build on Python 3.8
          python: 3.8
          script:
              - rkd :build

        - stage: Release to PyPI
          python: 3.6
          script:
              - rkd :build :publish --token="${PYPI_TOKEN}"
