version: org.riotkit.rkd/yaml/v1
imports:
    - rkd_python.BuildTask
tasks:
    :build:
        description: Build all packages
        steps: |
            #!python
            this: TaskInterface

            for name in ['rkt_armutils', 'rkt_utils', 'rkt_ciutils']:
                this.sh('cd packages/%s && rkd --silent :py:build' % name)

            return True

    :publish:
        description: Publish all packages
        arguments:
            "--token":
                required: true
                help: PyPI credentials
            "--test":
                action: store_true
                help: "Upload to test.pypi.org?"
        steps:
          - >
            #!python

            for module in ['rkt_armutils', 'rkt_utils', 'rkt_ciutils']:
                this.sh('cd packages/%s && rkd --silent :py:publish --user=__token__ --password=%s %s' % (
                    module,
                    ctx.args['token'],
                    ' --test ' if ctx.args['test'] else ''
                ))

            return True
